services:
  - type: web
    name: spacerisk-radar
    runtime: python
    branch: main
    autoDeployTrigger: commit
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
